### ISSUE TITLE
Take view full-screen into account

### ISSUE THREAD

**Issue by philiprenich** [filamentgroup/html-video-responsive#2]
One use-case I see missing from the summary so far is the use case of a video being played within the layout of a webpage - perhaps only taking up 1/4 of the available screen - and the user the clicking to go full-screen (at some point before or during play). I would like to see a way to initially present a small video file and then fetch the large version when the user requests full screen. 

Loading a 1080p or 4k video in case the user wants to go full screen is not a good experience for a mobile user or someone on a small laptop screen, or just someone who doens't want to bother leaving the webpage context.

I don't think this changes any scope or attributes proposed thus far, just an implementation use-case for the browser.

**Comment by phillipseamore** [comment]
It's actually a rather complicated case, as are all resize > change media situations while playing or having loaded media. This is only really solved by DASH or HLS and authoring the media according to the specifications. I haven't looked up the discussions from when the W3C changed the `<video>` spec but I wouldn't be surprised if these cases were the primary reason to abandon sizes support.

**Comment by philiprenich** [comment]
@phillipseamore Is there a difference between the `<video>` element resizing within the page and the video going fullscreen?
With the caveat that I don't know what I don't know and therefore it's much more complicated than I envision, is it not straight foward to capture the timestamp at the event to go fullscreen and start the larger video size at that spot?

**Comment by phillipseamore** [comment]
No there isn't any difference between changing sources based on resizing the window or going fullscreen. The issue is how to handle flushing the media that is already in the buffer, retrieving new media (higher or lower res file), seeking to right frame and audio sample and starting playback again. If the media isn't all authored correctly changing between files might completely stall. How the media is served would be an issue also (e.g. if the server doesn't support byte-range requests the whole file would be retrieved etc). There are a tonne of technical and UX issues.  This is all solved with HLS and DASH and authoring the media files according to those specs. None of this is an issue if the media hasn't been loaded and isn't playing - but that would be uncommon.
